//
// Created by Vico Tünke on 19.11.22.
//

#ifndef BETRIEBSSYSTEME_WS22_23_INTERRUPT_HANDLER_H
#define BETRIEBSSYSTEME_WS22_23_INTERRUPT_HANDLER_H

void abt_handler();

#endif //BETRIEBSSYSTEME_WS22_23_INTERRUPT_HANDLER_H
